import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

const font = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dream Agency",
  description: "Generated by Dream Agency Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
